name: Daily Countdown

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node update.js

      - name: Commit and Push
        run: |
          git config user.name "SEU_USUARIO"
          git config user.email "SEU_EMAIL_VERIFICADO"

          git add README.md contador.json

          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
          else
            git commit -m "daily update"
            git push
          fi
